-- =====================================================
-- TRAFFIC SOURCE ANALYSIS
-- =====================================================
-- Objective:
-- Analyse website traffic sources to understand
-- acquisition performance, session trends,
-- conversion efficiency, and revenue contribution.
-- =====================================================

-- TOTAL WEBSITE SESSIONS.  How much traffic does the business receive?

SELECT COUNT(DISTINCT website_session_id) AS total_sessions
FROM website_sessions;

-- SESSIONS BY TRAFFIC SOURCE.  Which marketing channels generate the most traffic?
  
SELECT 
    utm_source,
    COUNT(DISTINCT website_session_id) AS total_sessions
FROM website_sessions
GROUP BY utm_source
ORDER BY total_sessions DESC;

-- SESSIONS BY SOURCE AND CAMPAIGN.  

SELECT
    utm_source,
    utm_campaign,
    COUNT(DISTINCT website_session_id) AS total_sessions
FROM website_sessions
GROUP BY utm_source, utm_campaign
ORDER BY total_sessions DESC;

-- MONTHLY TRAFFIC TREND.  How has website traffic changed over time? 

SELECT
    DATE(created_at) AS session_date,
    COUNT(DISTINCT website_session_id) AS sessions
FROM website_sessions
GROUP BY session_date
ORDER BY session_date;

-- TOP TRAFFIC SOURCES OVER TIME.  Daily sessions by traffic source.

SELECT
    DATE(created_at) AS session_date,
    utm_source,
    COUNT(DISTINCT website_session_id) AS sessions
FROM website_sessions
GROUP BY session_date, utm_source
ORDER BY session_date;

-- DEVICE PERFORMANCE.  Which devices generate the most traffic?

SELECT
    device_type,
    COUNT(DISTINCT website_session_id) AS total_sessions
FROM website_sessions
GROUP BY device_type
ORDER BY total_sessions DESC;

-- SEGMENTATION.  Traffic source by device type

SELECT
    utm_source,
    device_type,
    COUNT(DISTINCT website_session_id) AS total_sessions
FROM website_sessions
GROUP BY utm_source, device_type
ORDER BY total_sessions DESC;

-- CONVERSION RATE BY TRAFFIC SOURCE.  Which traffic channels convert most efficiently?

SELECT
    ws.utm_source,
    
    COUNT(DISTINCT ws.website_session_id) AS sessions,
    
    COUNT(DISTINCT o.order_id) AS orders,

    ROUND(
        COUNT(DISTINCT o.order_id) * 100.0
        / COUNT(DISTINCT ws.website_session_id),
        2
    ) AS conversion_rate_percentage

FROM website_sessions ws

LEFT JOIN orders o
ON ws.website_session_id = o.website_session_id

GROUP BY ws.utm_source

ORDER BY conversion_rate_percentage DESC;

-- REVENUE GENERATED BY TRAFFIC SOURCE 

SELECT
    ws.utm_source,

    COUNT(DISTINCT o.order_id) AS total_orders,

    ROUND(SUM(o.price_usd), 2) AS total_revenue,

    ROUND(
        SUM(o.price_usd)
        / COUNT(DISTINCT ws.website_session_id),
        2
    ) AS revenue_per_session

FROM website_sessions ws

LEFT JOIN orders o
ON ws.website_session_id = o.website_session_id

GROUP BY ws.utm_source

ORDER BY total_revenue DESC;

-- =====================================================
-- KEY FINDINGS
-- =====================================================

-- Paid search generated the highest traffic volume.

-- Email traffic showed the strongest conversion rate,
-- indicating high intent customer engagement.

-- Mobile traffic represented a significant share
-- of sessions but underperformed in conversion efficiency.

-- Revenue per session varied considerably by channel,
-- suggesting differing traffic quality across acquisition sources.



